version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      postgres -c max_connections=200 -c fsync=off -c synchronous_commit=off -c
      full_page_writes=off
    volumes:
      - database-volume:/var/lib/postgresql/data
    ports:
      - '65342:65342'
    networks:
      - shared-network
    restart: on-failure
