version: '3.6'

volumes:
  postgres:

networks:
  test:
    name: app

services:
  db:
    image: postgres:9.6
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -c max_connections=200 -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: on-failure
  # pubsub:
  #   image: messagebird/gcloud-pubsub-emulator:latest
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_STAGE: dev
    volumes:
      - .:/usr/src/app
    command:
      - npm
      - run
      - start:main
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 31348:8080
    networks:
      default:
      test:
        aliases:
          - nodejs-app
